version: 2
updates:
  # Enable version updates for npm (JavaScript/Node.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "@dependabot[bot]"
    assignees:
      - "@dependabot[bot]"
    commit-message:
      prefix: "npm"
      include: "scope"
    # Group updates for related packages
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      testing-ecosystem:
        patterns:
          - "@testing-library/*"
          - "jest*"
      build-tools:
        patterns:
          - "webpack*"
          - "babel*"
          - "@babel/*"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore specific packages if needed (uncomment and modify as needed)
    # ignore:
    #   - dependency-name: "react"
    #     versions: ["17.x"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
