name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - '.eslintrc*'
      - '.prettierrc*'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - '.eslintrc*'
      - '.prettierrc*'

jobs:
  eslint:
    name: ESLint Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: |
        npx eslint src/ \
          --ext .js,.jsx,.ts,.tsx \
          --format json \
          --output-file eslint-report.json
      continue-on-error: true

    - name: Annotate code with ESLint results
      uses: ataylorme/eslint-annotate-action@v2
      if: always()
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        report-json: eslint-report.json

    - name: Upload ESLint report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: eslint-report
        path: eslint-report.json

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check code formatting
      run: |
        npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}" \
          "public/**/*.{html,json}" \
          "*.{js,json,md}"
      continue-on-error: true

    - name: Generate formatting report
      if: failure()
      run: |
        echo "## 💅 Code Formatting Issues Found" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The following files need formatting:" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        npx prettier --list-different "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}" "public/**/*.{html,json}" "*.{js,json,md}" >> $GITHUB_STEP_SUMMARY || true
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Run \`npm run format\` or \`npx prettier --write .\` to fix these issues." >> $GITHUB_STEP_SUMMARY
